#Denmark Market
def get_C20():
	data=['MAERSK-A.CO', 'MAERSK-B.CO', 'CARL-B.CO', 'CHR.CO', 'COLO-B.CO', 'DANSKE.CO', 'DSV.CO', 'FLS.CO', 'GEN.CO', 'GN.CO', 'LUN.CO', 'ISS.CO', 'JYSK.CO', 'NDA-DKK.CO', 'NOVO-B.CO', 'NZYM-B.CO', 'PNDORA.CO', 'TDC.CO', 'VWS.CO', 'WDH.CO']

#['DENERG.CO','NRDC.CO','VIINT.CO','NEUR.CO','JDAN.CO','DSV.CO','DANTH.CO','NZYM-B.CO','RBREW.CO','VWS.CO','GJ.CO','MAERSK-B.CO','VJBA.CO','SIM.CO','VIBHK.CO','WDH.CO','VIPRO.CO','SPEAS.CO','RBLN-B.CO','TIV.CO','SKAKO.CO','JOBNDX.CO','IC.CO','FED.CO','OJBA.CO','NOVO-B.CO','GN.CO','JYSK.CO','ALMB.CO','VELO.CO','ZEAL.CO','MNBA.CO','STYLE.CO','NNIT.CO','GERHSP-B.CO','RTX.CO','ESOFT.CO','SIF.CO','ISS.CO','BAVA.CO','SPG.CO','CARL-A.CO','EXQ.CO','ALK-B.CO','FLS.CO','GEN.CO','LUN.CO','MOLS.CO','SALB.CO','SYDB.CO','ROV.CO','SCHO.CO','PNDORA.CO','BIOPOR.CO','COLO-B.CO','TRYG.CO','BLVIS.CO','CHR.CO','TDC.CO','DANSKE.CO','TORM.CO','MERM.CO','TOP.CO','WIRTEK.CO']
	return data

#Sweden
def get_S30():
	data=['FALC','SOBI.ST','CAMT','SKIS','NAII','ADMS','WLDN','SYPR','TTHI','SNFCA','IIN','PAR.ST','ONFC','IMMU','STDY','DNAI','LARK','CBAK','ODD.ST','ARDX','SEB-A.ST','CRIS','INDT.ST','ITEK','AMTX','SYNC','ICA.ST','FCCY','EOLU-B.ST','FOLD','PLNR','HFFC','FWM','CBFV','WOWO','WTG.ST','CHRS','UFLX-B.ST','TOUR','ATAI','GOMO','OMER','RMGN','VSTM','NOLA-B.ST','FATE','MNDO','OPCO.ST','GFN','DEDI.ST','NEOS','VIAS','HILL','EDUC','BRID','FEIM','HBIO','AUPH','JAYS.ST','TNDM','XELB','ARGS','MFSF','QLRO.ST','OSTK','BSQR','XANO-B.ST','UNIB-SDB.ST','RICK','XTRA-BTA-1.ST','ZENI.ST','OCC','LAND','JM.ST','IJ.ST','NEWT','BEO-SDB.ST','CNSI','QFRO.ST','GKNT','DUNI.ST','SBOK.ST','EEI','ALOT','UNIS','MRNS','VBLT','LNBB','GOIL-PREF.ST','HFBC','MNKD','ANCX','EGRX','XOMA','CLUB','ANCB','KMPH','TBPH','AMRN','HMNF','EVK','ASRV','MVIS','QUIK','PRQR','KINV-A.ST','INSY','MAGS','BSF','KIDO.ST','XCOM','MOKO','AGRX','OLLI','ACRX','FES','SOCB','VICP-PREF.ST','HYGS','STIL.ST','KTEC','OTIV','STAA','TINY','EGLT','VNDA','FOMX','DOXA.ST','ZGNX','SLCT','III','GPP','ANAC','HOVNP','NVET','SBBX','CLLS','LWAY','RPTP','PXLW','MERU','VRG-B.ST','MPB','ZN','EAC','BWINA','WINA','HEXA-B.ST','ZENZIP.ST','ALIM','ADHD','TLSN.ST','MCUR','IESC','NCC-B.ST','MLVF','SOHOL','JCS','CPHR','FLXN','TSBK','TWW.ST','MIRN','RCMT','XVIVO.ST','VNV-SDB.ST','BKEP','BLBD','RGCO','VERI.ST','LENS','MOBI','XENE','OASM.ST','MB','PFAM.ST','NVLS','ARRY','NVSL','LACO','OSIR','GPIC','BLPH','MATR','SBSA','SPAN','ERIC-B.ST','OPUS.ST','SYNT.ST','FRPT','UTG.ST','AIQ','CSCD','WVFC','CARA','FING-B.ST','TNXP','FCEL','FULLL','VIDE','GFED','RWLK','ODEN.ST','QUICK.ST','VIMC','FNHC','CERU','NEXAM.ST','REZT.ST','ALDR','MHGC','OVBC','CSPI','PGLC','MODI.ST','AVGR','ZALO.ST','STRT','QCRH','LABC','NBN','CARB','QTNTW','LOXO','RDUS','KUTV','PIH','CGEN','CLBH','MDSY','FBMS','AKAO','AMOT','PTSI','ARQL','OLDM.ST','NYNY','SOHOM','OCYO.ST','SCYX','AAOI','PCMI','OCAT','USAT','NEVI-B.ST','OSHC','ISM','HEAR','BLDP','NGHCP','ENFC','NMAN.ST','EBIO','EVAR','CWBC','TACT','GFNCP','CDNA','JINO.ST','CEFO-UR.ST','NMIH','DTEA','KONA','CLFD','EBMT','UPLD','CMGE','DENT.ST','63649.ST','TTGT','CNCE','NERV','CNFR','INTX','CDORP','RDNT','LGND','CERS','PNBK','KABE-B.ST','BBGI','TKAI','CBAN','TLOG','AUBN','GLDC','EQL.ST','CORE.ST','AFMD','EDGW','TST','CYTX','203.ST','PBMD','DSWL','SYMX','CFNB','KBIO','GRIF','SNTA','UNTY','RNBS.ST','NLST','ELV.ST','FFWM','CBNK','CIZN','ZYNE','SALM','VBTX','UMED.ST','RABT-B.ST','CZFC','MSBF','RPD','MTG-B.ST','RUSF.ST','VOLV-B.ST','IRIX','EDAP','EARS','NGHCZ','ARKR','AQXP','HERO','RKDA','PETX','OFLX','ISTR','PRCP','CDON.ST','APWC','TRAD.ST','MSON','NVDQ','ATRC','LNTH','OCUL','SKF-B.ST','DRRX','MACK','ZZ-B.ST','BKEPP','CAPE.ST','NSTG','ESCA','HLG','CALL','HABT','CYHHZ','KINV-B.ST','SGC','FNWB','SAEX','PHI.ST','SKF-A.ST','LAKE','KEQU','MBII','UG','ENPH','NSEC','PGTI','WSTG','NAUH','GUID','SPU','EML','ROKA','CYNA','ANTH','CLCT','FLKS','RVNC','WVE','HIFS','FRBK','XENT','MISE.ST','MOB.ST','NCC-A.ST','ZSPH','FLML','GFNSL','ALLB','CDOR','ULBI','MDWD','EXA','SPPRP','LTRE','SAGE','RBPAA','BNFT','BLCM','USE-B.ST','STE-A.ST','SCMP','RTRX','OBAS','DEMI-B.ST','NDA-SEK.ST','ANY','DRAD','KNOW.ST','CLCD','ROOT.ST','OP-PREF.ST','VOLV-A.ST','TCON','WEIFAO.ST','ABTX','AJA-B.ST','SMTX','QUNR','PRTK','GENC','GLBS','FRBA','IMDZ','VTAE','PTX','HIIQ','GNMK','TLF','HALL','CPHC','CLDN','XLRN','KTCC','TATT','SNM-TR.ST','VCYT','IDSY','SMBC','NVFY','ASBB','OSM','NHTB','SPPRO','LLEX','AWRE','GWPH','NDRM','MCFT','WLB','BOCH','NLNK','SUPN','ENTL','RMTI','DOXA-BTA.ST','TRMO.ST','HNSN','XTRA.ST','MNOV','QLTY','PRPH','CMCT','YILD-B.ST','JOSA.ST','ONG.ST','MOCO','MZOR','GAI','AFOP','BSTC','NGHCO','ACFC','76466.ST','KLOV.ST','GCVRZ','VIRC','USATP','BUR','UNAM','HTGM','UBOH','SKA-B.ST','MFRI','NEOT','LBIO','MEDA-A.ST','AAVL','BVSN','UCBA','OVAS','CBYL','ANIP','CWS.ST','RGLS','QBNK.ST','MGYR','PSDV','PALS-B.ST','MAG','SONA','JMBA','VINO.ST','VICP-A.ST','ZETA.ST','CCCL','APPF','AHPI','CEFO-B.ST','VTVT','DXYN','HCAP','PRMW','QCCO','MBUU','GAIA','BALD-B.ST','KLED.ST','INNL','NGHC','TRNS','PEBK','CMRX','SNMX','UNB','ORTI-B.ST','SAMG','ESPR','TRCB','FULL','LMAT','CPSS','DYAX','ERIC-A.ST','PFPT','FIVN','FGBI','NWFL','GLYC','STVA-B.ST','TWMC','HMTV','SMMT','KDEV.ST','EMKR','CNXR','AEY','TTOO','WMGIZ','ALM-PREF.ST','CXDC','PBIP','PFIN','KARO.ST','SSRG','FMBH','76465.ST','RFIL','AGTC','PAHC','AAME','WLFC','PFBI','CCUR','VIVO-UR.ST','NAXS.ST','NIOO.ST','PARN','AKBA','SSBI','ARTX','LMRK','CZWI','GNCA','PWX','CNAT','RMCF','NTIC','CDZI','SHBA.ST','DRIL.ST','BWFG','SFST','SIFI','XNCR','WAYN','HM-B.ST','CYBE','BWINB','HPJ','NETI-B.ST','KAHL.ST','CALD','CORI','OCRX','AERI','MESG','HUSQ-B.ST','BCS.ST','OBAB.ST','CBMG','SOHO','JSM','QTNT','NECB','SHB-A.ST','CATB','NVIV','VBG-B.ST','FENX','PFE.ST','SYNL','ORPN','EKTA-B.ST','XXLO.ST','CELGZ','BCBP','KFFB','TSRE','GDEN','HSGX','CVLY','SORL','TREL-B.ST','WESC.ST','ORTI-A.ST','NOVE.ST','IKGH','OXFD']

#Norway
def get_O20():
	data=['HSPG.OL','SVEG.OL','SOFF.OL','OCY.OL','NEL.OL','HNA.OL','DOLP.OL','ENTRA.OL','ODL.OL','VISTIN.OL','SDRL.OL','TGS.OL','VVL.OL','SSC.OL','SEVDR.OL','GJF.OL','REACH.OL','VLCCF.OL','NIO.OL','SCH.OL','SEVAN.OL','TTS.OL','MCG.OL','AKSO.OL','NORTH.OL','RING.OL','ITE.OL','DMABB.OL','MSEIS.OL','QEC.OL','DESSC.OL','NATTO.OL','OLT.OL','NPRO.OL','MING.OL','TOTG.OL','JIN.OL','WILS.OL','GSF.OL','DETNOR.OL','HELG.OL','REC.OL','STL.OL','QFR.OL','SSI.OL','AFG.OL','PLCS.OL','ODFB.OL','CXENSE.OL','YARFUT.OL','SSO.OL','FAR.OL','NTS.OL','TEL.OL','HFISK.OL','VIZ.OL','MHG.OL','WRL.OL','ZAL.OL','DNO.OL','PSI.OL','DNB.OL','BWO.OL','ZONC.OL','EKO.OL','VEI.OL','EMAS.OL','KOG.OL','ASC.OL','PHO.OL','BLO.OL','WWI.OL','PEN.OL','SER.OL','HEX.OL','XXL.OL','BEL.OL','THIN.OL','SPU.OL','OPERA.OL','NMG.OL','SONG.OL','SBVG.OL','ELT.OL','PGS.OL','OTS.OL','NAS.OL','ITX.OL','BAKKA.OL','NAPA.OL','NRS.OL','SOLV.OL','WWASA.OL','EIOF.OL','GRO.OL','STORM.OL','SRBANK.OL','AWDR.OL','TOM.OL','MEDI.OL','REM.OL','NHY.OL','NSG.OL','GOGL.OL','DOF.OL','SCI.OL','YAR.OL']
	
#Germany
#def get_DAX30():
#	data=

#England
#def get_FTSE100():
	
#USA

#def get_DOWJONES():
	
#def get_NAS100():

#def get_SPX500():

#Japan
#def get_NIKKEI():
	
#HongKong
#def get_HKG33():

#USA Oil
#get_WTICRUDE():

#EU Oil
#get_BRENTOIL():
